export interface Tool {
  slug: string
  name: string
  description: string
  shortDescription: string
  category: 'developer-tools'
  icon: string
  searchKeyword: string
  monthlySearches: number
  competition: 'none' | 'very low' | 'low' | 'medium' | 'high'
  buildPriority: number
  proFeature: string
  color: string
}

export const TOOLS: Tool[] = [
  // === DEVELOPER TOOLS ===
  {
    slug: 'password-generator',
    name: 'Password Generator',
    description: 'Generate strong, secure passwords instantly. Customize length, symbols, numbers, and uppercase letters.',
    shortDescription: 'Generate strong passwords instantly',
    category: 'developer-tools',
    icon: 'Lock',
    searchKeyword: 'password generator',
    monthlySearches: 12000,
    competition: 'high',
    buildPriority: 4,
    proFeature: 'Secure vault, breach check',
    color: 'slate'
  },
  {
    slug: 'qr-code-generator',
    name: 'QR Code Generator',
    description: 'Generate QR codes for free. Enter any URL or text and get a downloadable QR code. No signup required.',
    shortDescription: 'Create QR codes for free',
    category: 'developer-tools',
    icon: 'QrCode',
    searchKeyword: 'qr code generator',
    monthlySearches: 10000,
    competition: 'high',
    buildPriority: 4,
    proFeature: 'Custom colors, logo, analytics',
    color: 'violet'
  },
  {
    slug: 'unix-timestamp-converter',
    name: 'Unix Timestamp Converter',
    description: 'Convert Unix timestamps to human-readable dates and vice versa. Free online tool for developers to work with epoch time, seconds, and milliseconds.',
    shortDescription: 'Convert Unix epoch time to date and back',
    category: 'developer-tools',
    icon: 'Clock',
    searchKeyword: 'unix timestamp converter',
    monthlySearches: 600000,
    competition: 'medium',
    buildPriority: 5,
    proFeature: 'Batch conversion, history, export',
    color: 'blue'
  },
  {
    slug: 'api-response-validator',
    name: 'API Response Validator',
    description: 'Format, validate, and parse HTTP response headers and JSON bodies online. Inspect HTTP status codes, trace errors, and generate TypeScript interfaces locally.',
    shortDescription: 'Format, validate and parse HTTP headers & JSON',
    category: 'developer-tools',
    icon: 'Terminal',
    searchKeyword: 'api response validator',
    monthlySearches: 45000,
    competition: 'low',
    buildPriority: 5,
    proFeature: 'Full history logs, batch response parsing, XML/YAML payloads',
    color: 'blue'
  },
  {
    slug: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Format, validate, and beautify JSON data online. Paste your JSON and get properly indented output instantly. No server upload needed.',
    shortDescription: 'Format and validate JSON online',
    category: 'developer-tools',
    icon: 'Code',
    searchKeyword: 'json formatter',
    monthlySearches: 800000,
    competition: 'medium',
    buildPriority: 3,
    proFeature: 'Minify, tree view, export',
    color: 'blue'
  },
  {
    slug: 'base64-encoder',
    name: 'Base64 Encoder/Decoder',
    description: 'Encode and decode Base64 text online. Convert text to Base64 and back. Client-side processing, no data leaves your browser.',
    shortDescription: 'Encode/decode Base64 online',
    category: 'developer-tools',
    icon: 'Code',
    searchKeyword: 'base64 encoder decoder',
    monthlySearches: 500000,
    competition: 'low',
    buildPriority: 3,
    proFeature: 'File to Base64, batch encode',
    color: 'slate'
  },
  {
    slug: 'hash-generator',
    name: 'Hash Generator',
    description: 'Generate MD5, SHA-1, SHA-256, SHA-512, and HMAC hashes from text. Supports batch hashing for multiple lines and custom keys.',
    shortDescription: 'Generate secure MD5, SHA, and HMAC hashes',
    category: 'developer-tools',
    icon: 'Hash',
    searchKeyword: 'hash generator md5 sha hmac',
    monthlySearches: 400000,
    competition: 'low',
    buildPriority: 5,
    proFeature: 'Unlimited batch items, CSV export',
    color: 'emerald'
  },
  {
    slug: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test regular expressions online. Enter your regex pattern and test string to see matches, groups, and replacements in real time.',
    shortDescription: 'Test regular expressions online',
    category: 'developer-tools',
    icon: 'Code',
    searchKeyword: 'regex tester',
    monthlySearches: 400000,
    competition: 'medium',
    buildPriority: 2,
    proFeature: 'Save patterns, cheat sheet',
    color: 'amber'
  },
  {
    slug: 'url-encoder',
    name: 'URL Encoder/Decoder',
    description: 'Encode and decode URLs online. Convert special characters to URL-safe format and back. Client-side processing.',
    shortDescription: 'Encode/decode URLs online',
    category: 'developer-tools',
    icon: 'Link',
    searchKeyword: 'url encoder decoder',
    monthlySearches: 400000,
    competition: 'low',
    buildPriority: 2,
    proFeature: 'Batch encode, form data encoder',
    color: 'slate'
  },
  {
    slug: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate random UUIDs (v4) online. Create one or multiple UUIDs instantly. Copy to clipboard with one click.',
    shortDescription: 'Generate random UUIDs online',
    category: 'developer-tools',
    icon: 'Hash',
    searchKeyword: 'uuid generator',
    monthlySearches: 200000,
    competition: 'low',
    buildPriority: 2,
    proFeature: 'UUID v1/v3/v5, bulk generation',
    color: 'indigo'
  },
  {
    slug: 'hex-to-rgb',
    name: 'Hex to RGB Converter',
    description: 'Convert hex color codes to RGB and HSL values. Free online color converter for designers and developers.',
    shortDescription: 'Convert hex to RGB color codes',
    category: 'developer-tools',
    icon: 'Palette',
    searchKeyword: 'hex to rgb converter',
    monthlySearches: 600000,
    competition: 'medium',
    buildPriority: 2,
    proFeature: 'Color palette, contrast checker',
    color: 'purple'
  },
  {
    slug: 'binary-converter',
    name: 'Binary Converter',
    description: 'Convert between binary, decimal, octal, and hexadecimal number systems. Free online number base converter.',
    shortDescription: 'Convert between number systems',
    category: 'developer-tools',
    icon: 'Binary',
    searchKeyword: 'binary converter',
    monthlySearches: 200000,
    competition: 'low',
    buildPriority: 2,
    proFeature: 'ASCII/binary, bitwise operations',
    color: 'slate'
  },
  {
    slug: 'code-formatter',
    name: 'Code Formatter',
    description: 'Format and beautify HTML, CSS, and JavaScript code online. Free code formatter with instant preview.',
    shortDescription: 'Beautify HTML, CSS, and JavaScript code',
    category: 'developer-tools',
    icon: 'Braces',
    searchKeyword: 'code formatter online',
    monthlySearches: 800000,
    competition: 'medium',
    buildPriority: 4,
    proFeature: 'Format TypeScript, JSON, Python; save snippets',
    color: 'violet'
  },
  {
    slug: 'json-csv-converter',
    name: 'JSON to CSV Converter',
    description: 'Convert JSON to CSV or CSV to JSON online for free. Instant two-way conversion, no upload required.',
    shortDescription: 'Convert JSON ↔ CSV instantly',
    category: 'developer-tools',
    icon: 'ArrowLeftRight',
    searchKeyword: 'json to csv converter',
    monthlySearches: 500000,
    competition: 'medium',
    buildPriority: 4,
    proFeature: 'Batch convert files, custom delimiters, save history',
    color: 'cyan'
  },
  {
    slug: 'yaml-json-converter',
    name: 'YAML to JSON Converter',
    description: 'Convert YAML to JSON and JSON to YAML online. Safe, client-side conversion with live error highlighting, copy, and download. No signup required.',
    shortDescription: 'Convert YAML ↔ JSON online instantly',
    category: 'developer-tools',
    icon: 'ArrowRightLeft',
    searchKeyword: 'yaml to json converter',
    monthlySearches: 600000,
    competition: 'low',
    buildPriority: 5,
    proFeature: 'Batch file conversion, custom indentation, and alphabetical key sorting',
    color: 'blue'
  },
  {
    slug: 'diff-checker',
    name: 'Diff Checker',
    description: 'Compare two texts or code blocks and see the differences highlighted. Free online diff tool with side-by-side view.',
    shortDescription: 'Compare two texts and highlight differences',
    category: 'developer-tools',
    icon: 'GitCompare',
    searchKeyword: 'diff checker online',
    monthlySearches: 600000,
    competition: 'medium',
    buildPriority: 4,
    proFeature: 'Download diff report, file upload, ignore whitespace',
    color: 'green'
  },
  {
    slug: 'markdown-editor',
    name: 'Markdown Editor',
    description: 'Write and preview Markdown in real time. Free online Markdown editor with live preview. Auto-saves to browser.',
    shortDescription: 'Live-preview markdown editor online',
    category: 'developer-tools',
    icon: 'FileText',
    searchKeyword: 'markdown editor online',
    monthlySearches: 700000,
    competition: 'medium',
    buildPriority: 4,
    proFeature: 'Export to PDF/HTML, multiple files, custom themes',
    color: 'indigo'
  },
  {
    slug: 'html-playground',
    name: 'HTML Playground',
    description: 'Write HTML, CSS, and JavaScript and see a live preview instantly. Free mini CodePen alternative, no signup needed.',
    shortDescription: 'Live HTML/CSS/JS preview playground',
    category: 'developer-tools',
    icon: 'Monitor',
    searchKeyword: 'html css js playground',
    monthlySearches: 400000,
    competition: 'medium',
    buildPriority: 4,
    proFeature: 'Save & share snippets, embed on any page',
    color: 'orange'
  },
  {
    slug: 'qr-code-decoder',
    name: 'QR Code Decoder',
    description: 'Decode QR codes from an uploaded image. Free online QR reader — no camera, no app needed. Instant results.',
    shortDescription: 'Read and decode QR codes from images',
    category: 'developer-tools',
    icon: 'ScanSearch',
    searchKeyword: 'qr code decoder online',
    monthlySearches: 300000,
    competition: 'low',
    buildPriority: 4,
    proFeature: 'Batch decode, history log, export results',
    color: 'slate'
  },
  {
    slug: 'webhook-tester',
    name: 'Webhook Tester',
    description: 'Generate mock webhook payloads for Stripe, Shopify, and GitHub. Send test requests to local endpoints and inspect responses.',
    shortDescription: 'Simulate and test webhooks locally',
    category: 'developer-tools',
    icon: 'Terminal',
    searchKeyword: 'webhook tester',
    monthlySearches: 50000,
    competition: 'very low',
    buildPriority: 5,
    proFeature: 'Save unlimited history, send custom authorization tokens, and export test reports',
    color: 'blue'
  },
  {
    slug: 'jwt-decoder',
    name: 'JWT Decoder',
    description: 'Decode and inspect JSON Web Tokens (JWT) locally and securely. Base64 decode header and payload parts, view expiration countdown timers, and inspect standard claims.',
    shortDescription: 'Decode and inspect JSON Web Tokens locally',
    category: 'developer-tools',
    icon: 'Key',
    searchKeyword: 'jwt decoder',
    monthlySearches: 950000,
    competition: 'low',
    buildPriority: 5,
    proFeature: 'Advanced signature verification (HS/RS/ES keys), JWKS endpoints, and automatic claims validation policy profiles',
    color: 'blue'
  },
  {
    slug: 'cron-expression-builder',
    name: 'Cron Expression Builder',
    description: 'Build cron expressions visually. Select values for minute, hour, day-of-month, month, and day-of-week fields with instant human-readable translation and preset schedules.',
    shortDescription: 'Build cron expressions with visual selectors',
    category: 'developer-tools',
    icon: 'Timer',
    searchKeyword: 'cron expression builder generator',
    monthlySearches: 350000,
    competition: 'low',
    buildPriority: 5,
    proFeature: 'Next 5 fire times preview, calendar view, custom presets library',
    color: 'green'
  },
  {
    slug: 'curl-to-code',
    name: 'cURL to Code Converter',
    description: 'Convert cURL commands to Fetch, Axios, Python, and Go code instantly. Paste a cURL command from your terminal or API docs and get production-ready code.',
    shortDescription: 'Convert cURL commands to native API code',
    category: 'developer-tools',
    icon: 'Terminal',
    searchKeyword: 'curl to code converter',
    monthlySearches: 250000,
    competition: 'low',
    buildPriority: 5,
    proFeature: 'Convert to all languages at once, shareable code snippets, request preview',
    color: 'blue'
  },
  {
    slug: 'gitignore-generator',
    name: '.gitignore Generator',
    description: 'Generate .gitignore files by combining templates for Node.js, Python, Go, Rust, Java, Docker, and more. Free online .gitignore generator with custom rules.',
    shortDescription: 'Generate .gitignore files from templates',
    category: 'developer-tools',
    icon: 'GitBranch',
    searchKeyword: 'gitignore generator online',
    monthlySearches: 400000,
    competition: 'low',
    buildPriority: 5,
    proFeature: 'Unlimited template combinations, team sharing, custom template builder',
    color: 'slate'
  },
  {
    slug: 'code-playground',
    name: 'Code Playground',
    description: 'Multi-language online code editor supporting 25+ languages. Write and run JavaScript, TypeScript, Python, and HTML live in your browser. Syntax highlighting, auto-save, and download.',
    shortDescription: 'Multi-language code editor with live execution',
    category: 'developer-tools',
    icon: 'FileCode',
    searchKeyword: 'code playground online editor',
    monthlySearches: 450000,
    competition: 'high',
    buildPriority: 4,
    proFeature: 'Collaborative editing, custom themes, embeddable snippets, AI code suggestions',
    color: 'violet'
  },
  {
    slug: 'json-to-typescript',
    name: 'JSON to TypeScript Interface Generator',
    description: 'Convert JSON objects into TypeScript interfaces instantly. Paste JSON and get typed interfaces, enums, and nested type definitions with one click.',
    shortDescription: 'Generate TypeScript interfaces from JSON',
    category: 'developer-tools',
    icon: 'Braces',
    searchKeyword: 'json to typescript interface generator',
    monthlySearches: 500000,
    competition: 'medium',
    buildPriority: 5,
    proFeature: 'Export to .d.ts, strict null checks option, multi-source merge',
    color: 'blue'
  },
  {
    slug: 'svg-to-jsx',
    name: 'SVG to React/JSX Converter',
    description: 'Convert SVG markup to React JSX component syntax instantly. Handles attributes, camelCase props, and inline styles for React, Preact, and Vue.',
    shortDescription: 'Convert SVG to React JSX components online',
    category: 'developer-tools',
    icon: 'Code',
    searchKeyword: 'svg to react jsx converter',
    monthlySearches: 200000,
    competition: 'low',
    buildPriority: 5,
    proFeature: 'Export as TypeScript component with props interface, batch SVG conversion, icon set packager',
    color: 'violet'
  },
  {
    slug: 'meta-tag-generator',
    name: 'Meta Tag / OG Preview Generator',
    description: 'Generate and preview Open Graph meta tags for Facebook, Twitter, and LinkedIn. See how your page will look when shared on social media.',
    shortDescription: 'Generate and preview social media OG meta tags',
    category: 'developer-tools',
    icon: 'Link',
    searchKeyword: 'meta tag generator og preview',
    monthlySearches: 150000,
    competition: 'low',
    buildPriority: 4,
    proFeature: 'JSON-LD schema generator, social card mockup, multi-platform preview',
    color: 'green'
  },
  {
    slug: 'robots-sitemap-generator',
    name: 'Robots.txt & Sitemap Generator',
    description: 'Generate robots.txt and XML sitemaps for your website. Create SEO-ready crawler directives and submit to search engines for indexing.',
    shortDescription: 'Create robots.txt and XML sitemaps for SEO',
    category: 'developer-tools',
    icon: 'Search',
    searchKeyword: 'robots txt sitemap generator',
    monthlySearches: 180000,
    competition: 'low',
    buildPriority: 4,
    proFeature: 'Auto-sitemap from URL crawler, multi-language hreflang, priority bulk edit',
    color: 'indigo'
  },
  {
    slug: 'css-grid-generator',
    name: 'CSS Grid & Flexbox Generator',
    description: 'Visual CSS Grid and Flexbox layout generator. Create responsive layouts with a visual interface, copy the generated CSS code instantly.',
    shortDescription: 'Visual CSS Grid and Flexbox layout builder',
    category: 'developer-tools',
    icon: 'LayoutGrid',
    searchKeyword: 'css grid generator flexbox builder',
    monthlySearches: 300000,
    competition: 'medium',
    buildPriority: 4,
    proFeature: 'Tailwind CSS output, responsive breakpoints preview, layout export library',
    color: 'purple'
  },
  {
    slug: 'iban-validator',
    name: 'IBAN & SWIFT Validator',
    description: 'Validate and parse IBAN numbers and SWIFT/BIC codes. Check IBAN structure, country, and checksum for 80+ countries worldwide.',
    shortDescription: 'Validate IBAN numbers and SWIFT codes',
    category: 'developer-tools',
    icon: 'FileCheck',
    searchKeyword: 'iban validator swift bic check',
    monthlySearches: 250000,
    competition: 'low',
    buildPriority: 4,
    proFeature: 'Batch validation CSV upload, bank name lookup, regex export for developers',
    color: 'green'
  },
  {
    slug: 'dns-ssl-checker',
    name: 'DNS Lookup & SSL Checker',
    description: 'Lookup DNS records (A, AAAA, CNAME, MX, NS, TXT) and check SSL certificate validity, expiration, and chain for any domain. Free online network diagnostic tool.',
    shortDescription: 'Lookup DNS records and verify SSL certificates',
    category: 'developer-tools',
    icon: 'Shield',
    searchKeyword: 'dns lookup ssl checker online',
    monthlySearches: 200000,
    competition: 'low',
    buildPriority: 4,
    proFeature: 'Historical DNS change tracking, SSL chain analyzer, email alerts on expiry',
    color: 'blue'
  }
]

export const CATEGORIES = [
  { slug: 'developer-tools', name: 'Developer Tools', icon: 'Code', description: 'JSON, Base64, regex, UUID, password, code formatter, diff, and playground', order: 1 }
]

export const SITE_CONFIG = {
  name: 'KRUMB.DEV',
  tagline: 'Developer tools for the modern web',
  description: 'Free online developer tools. No signup required. Instant results.',
  url: 'https://krumb.dev',
  socialLinks: {
    github: 'https://github.com/krumbdev',
    twitter: 'https://x.com/krumbdev',
    email: 'hello@krumb.dev'
  }
}

export const BUILT_TOOLS = [
  'password-generator',
  'qr-code-generator',
  'unix-timestamp-converter',
  'api-response-validator',
  'json-formatter',
  'base64-encoder',
  'hash-generator',
  'regex-tester',
  'url-encoder',
  'uuid-generator',
  'hex-to-rgb',
  'binary-converter',
  'code-formatter',
  'json-csv-converter',
  'yaml-json-converter',
  'diff-checker',
  'markdown-editor',
  'html-playground',
  'qr-code-decoder',
  'webhook-tester',
  'jwt-decoder',
  'cron-expression-builder',
  'curl-to-code',
  'gitignore-generator',
  'code-playground',
  'json-to-typescript',
  'svg-to-jsx',
  'meta-tag-generator',
  'robots-sitemap-generator',
  'css-grid-generator',
  'iban-validator',
  'dns-ssl-checker'
]

// Featured tools shown on the home page (not all 21 to avoid endless scrolling)
export const FEATURED_TOOLS = [
  'jwt-decoder',
  'json-formatter',
  'password-generator',
  'hash-generator',
  'uuid-generator',
  'code-formatter',
  'diff-checker',
  'markdown-editor',
]